name: Build and test dotnet app

on:
  push:
    branches: 
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Restore dependencies
        run: dotnet restore AccountMS/AccountMS.sln
        
      - name: Build project
        run: dotnet build AccountMS/AccountMS.csproj

      - name: Run tests
        run: dotnet test --no-restore AccountMS/AccountMS.sln
